version: 2

builds:
  - binary: tinfoil
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

dockers_v2:
  - images:
      - "ghcr.io/tinfoilsh/tinfoil-cli"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
